### ISSUE TITLE
Problem with accessing elements from details page

### ISSUE THREAD

**Issue by SimonPrimetzhofer** [rstropek-teaching/pokelist-quiz-4ahif-SimonPrimetzhofer#1]
Dear Mr. Stropek!

I have got a problem... 
I have already created the list of pokemons and the navigation buttons.
My problem is that I cannot access the elements of "detail.html" from my "app.ts" script, it only delivers null when I use document.getElementBy(id).

How can I solve this problem? I couldn't find any working solution on the internet.

By the way here is a link, if you want to try my current solution:
https://rawgit.com/rstropek-teaching/pokelist-quiz-4ahif-SimonPrimetzhofer/master/index.html

I used bootstrap.css for styling the HTML-Pages.

Greetings,
Simon Primetzhofer

**Comment by rstropek** [comment]
Hi @SimonPrimetzhofer!

I cloned your solution and debugged it. `document.getElementById` works perfectly fine on my computer, even in *default.html*. `pWeight` is *null* because it is called `pWeight` in HTML but you query for id `weight` in JavaScript (see [here](https://github.com/rstropek-teaching/pokelist-quiz-4ahif-SimonPrimetzhofer/blob/master/app.ts#L4)). Maybe that's your problem?

Greetings,
Rainer Stropek

**Comment by SimonPrimetzhofer** [comment]
Dear Mr. Stropek!

Actually I didn‘t work on with pWeight and the other elements... I only tried it with pName and this one delivers null. So it also doesn‘t insert the name.

Greetings,
Simon Primetzhofer

**Comment by rstropek** [comment]
Not on my PC. `pName` gets a value. It is not null.

![pname](https://user-images.githubusercontent.com/2341573/32993939-11129864-cd60-11e7-9e4a-69e8264011b3.png)
